### ISSUE TITLE
Plugin breaks startify

### ISSUE THREAD

**Issue by thepenguinthatwants** [Shatur95/neovim-session-manager#1]
Using, this plugin it seems to break startify and just starts a empty buffer.

**Comment by Shatur95** [comment]
The plugin loads last session by default. Set `g:autoload_last_session` if you want to see Startify instead.

**Comment by thepenguinthatwants** [comment]
Can you give more easier example.

I switched to lua recently.

```
require('telescope').load_extension('session_manager')
require('neovim-session-manager').setup {
    autoload_last_session = false
}

```

Tried setting it like this, but didn't seem to work.

**Comment by Shatur95** [comment]
For lua just put this line anywhere:
vim.g.autoload_last_sessi`on = true`.
You do not need to call `setup`.

Yes, all previous buffers will be discarded.

**Comment by thepenguinthatwants** [comment]
So I am trying to make this that it doesn't start at bootup and be able to read my sessions from ~/.config/nvim/session/ so I can switch from session to another, without messing the session buffers and locations.

What I tried was this.


```
vim.g.autoload_last_session = false
vim.g.session_dir = '~/.config/nvim/session/'
require('telescope').load_extension('session_manager')
```
Running 
`:LoadSession`
I get

E5107: Error loading lua [string ":lua"]:1: unexpected symbol near ','


Any clue how to debug or what I might have misconfigured


`:Telescope session_manager discard_and_load`
is not showing the sessions that I want.

**Comment by Shatur95** [comment]
> E5107: Error loading lua [string ":lua"]:1: unexpected symbol near ','

My bad, will work now. I just usually use Telescope to load sessions.

>  is not showing the sessions that I want.

This means that you do not have any session. Try `:Telescope session_manager load`.

**Comment by thepenguinthatwants** [comment]
Seems like 

`vim.g.autoload_last_session = False`

Doesn't get respected and after updating the plugin I still get.



`    E5107: Error loading lua [string ":lua"]:1: unexpected symbol near ','`

**Comment by Shatur95** [comment]
> vim.g.autoload_last_session = False

Lua do not have `False`. You should use `false`.

> E5107: Error loading lua [string ":lua"]:1: unexpected symbol near ','

Try now.

**Comment by thepenguinthatwants** [comment]
Hi,
Thanks so now it actually respects the setting

`vim.g.autoload_last_session = false`

but not sure if these are effective

```
vim.g.session_dir = '~/.config/nvim/session/'
require('telescope').load_extension('session_manager')
```
Altho I get no errors from 



:Telescope session_manager discard_and_load
Instead of showing sessions it seems to be showing folder locations of  last visited folders or something.

**Comment by Shatur95** [comment]
> vim.g.session_dir = '~/.config/nvim/session/'

Because you should use `sessions_dir`.
>  Instead of showing sessions it seems to be showing folder locations of last visited folders or something.

Yes, this is how sessions works.  Have you tried to read the readme?
